# Generated by Django 5.1.1 on 2024-10-02 05:32

import app_users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_customer_usermodel_is_admin_usermodel_is_customer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', app_users.models.UserModelManager()),
            ],
        ),
    ]
